### ISSUE TITLE
Changement de bank pour la mise en monitor

### ISSUE THREAD

**Issue by wargreen** [davidonet/bugNbuzz#6]
Impossible de retrouver comment ca fonctionne...

**Comment by wargreen** [comment]
Traceback (most recent call last):
  File "./osc_sooperlooper_test.py", line 155, in <module>
    server = MyServer()
  File "./osc_sooperlooper_test.py", line 36, in __init__
    self.stdscr.addstr(24,0,"     stop     ",curses.A_REVERSE)
_curses.error: addstr() returned ERR

**Comment by wargreen** [comment]
c ici pour échanger les gas ?    je viens de poster les message d'erreur que je rencontre ...  la cession ne démarre pas ...
